import { defineField, defineType } from 'sanity'

export const leadType = defineType({
  name: 'lead',
  title: 'Leads',
  type: 'document',
  fields: [
    defineField({ name: 'formType', title: 'Form type', type: 'string', options: { list: ['contact', 'coa'] }, validation: (Rule) => Rule.required() }),
    defineField({ name: 'name', title: 'Name', type: 'string', validation: (Rule) => Rule.required() }),
    defineField({ name: 'company', title: 'Company', type: 'string' }),
    defineField({ name: 'email', title: 'Email', type: 'string', validation: (Rule) => Rule.required().email() }),
    defineField({ name: 'phone', title: 'Phone / WhatsApp', type: 'string' }),
    defineField({ name: 'interest', title: 'Interest', type: 'string' }),
    defineField({ name: 'message', title: 'Message', type: 'text', rows: 6 }),
    defineField({ name: 'industry', title: 'Industry', type: 'string' }),
    defineField({ name: 'productName', title: 'Product', type: 'string' }),
    defineField({ name: 'quantity', title: 'Quantity', type: 'string' }),
    defineField({ name: 'role', title: 'Role', type: 'string' }),
    defineField({ name: 'demand', title: 'Annual demand', type: 'string' }),
    defineField({ name: 'application', title: 'Application', type: 'array', of: [{ type: 'string' }] }),
    defineField({ name: 'coaUrl', title: 'COA URL', type: 'url' }),
    defineField({ name: 'sourcePage', title: 'Source page', type: 'url' }),
    defineField({ name: 'submittedAt', title: 'Submitted at', type: 'datetime', validation: (Rule) => Rule.required() }),
    defineField({ name: 'status', title: 'Status', type: 'string', options: { list: ['new', 'email_failed'] } }),
    defineField({ name: 'teamEmailStatus', title: 'Team email', type: 'string', options: { list: ['pending', 'sent', 'failed'] } }),
    defineField({ name: 'autoReplyStatus', title: 'Auto-reply', type: 'string', options: { list: ['pending', 'sent', 'failed'] } }),
    defineField({ name: 'submissionId', title: 'Submission ID', type: 'string', readOnly: true }),
  ],
  preview: { select: { title: 'name', subtitle: 'email' } },
})
