// src/lib/mockData.ts — High quality B2B mock data fallback
import type { SanityProduct, SanityPost } from './sanity';

export const MOCK_CATEGORIES = [
  { _id: 'cat-1', name: 'Health Supplements', slug: 'health-supplements', description: 'Active pharmaceutical and nutraceutical ingredients.', icon: '💊', color: '#d4a654' },
  { _id: 'cat-2', name: 'Cosmetic Actives', slug: 'cosmetic-actives', description: 'Bioactive compounds for anti-aging and whitening formulas.', icon: '✨', color: '#e07830' },
  { _id: 'cat-3', name: 'Pet Health', slug: 'pet-health', description: 'High-purity ingredients for animal wellness and feeds.', icon: '🐾', color: '#f0c878' },
  { _id: 'cat-4', name: 'Custom Formulation', slug: 'custom-formulation', description: 'Tailored purity levels and custom botanical blends.', icon: '🧪', color: '#c8965a' }
];

export const MOCK_PRODUCTS: (SanityProduct & { description?: any; specifications?: any; coaFile?: any; msdsFile?: any; seo?: any; gallery?: any })[] = [
  {
    _id: "0da4b973-f06b-44f5-956d-cce836fee497",
    name: "PDRN (Polydeoxyribonucleotide) — Bulk Cosmetic Raw Material",
    slug: "pdrn",
    category: { name: "cosmetic-ingredients", slug: "cosmetic-ingredients" },
    categories: [{ name: "cosmetic-ingredients", slug: "cosmetic-ingredients" }, { name: "superfood", slug: "superfood" }],
    botanicalName: "Salmon (Oncorhynchus keta) sperm DNA-derived polydeoxyribonucleotide",
    purity: "≥ 90.0% (standard) / ≥ 98.0% (premium) — HPLC",
    activeIngredient: "Polydeoxyribonucleotide (PDRN) / Sodium DNA",
    casNumber: "100403-24-5",
    shortDescription: "Factory-direct PDRN bulk powder — salmon-derived (95% human-DNA homology) & plant-based vegan (Lactobacillus) grades, fully segregated supply chains. MOQ from 10g. Clinically validated for skin regeneration, anti-aging, wound healing. >=90%/>=98% purity. COA per batch.",
    shortDescription_ru: "ПДРН (полидезоксирибонуклеотид) оптом — две марки: из ДНК лосося (95% гомология с ДНК человека) и веганская (ферментация Lactobacillus), с разделёнными цепочками поставок. Мин. партия 10 г. Клинически подтверждено: регенерация, антивозрастной уход, заживление. Чистота >=90% / >=98%. COA на партию.",
    shortDescription_es: "Polvo a granel de PDRN (polidesoxirribonucleótido) — grados: de salmón (95% homología ADN humano) y vegano (fermentación Lactobacillus). MOQ desde 10g. Validado para regeneración cutánea, antienvejecimiento, cicatrización. >=90%/>=98% pureza. COA por lote. Cadenas segregadas.",
    shortDescription_ar: "بودرة PDRN (بولي دي أوكسي ريبونوكليوتيد) بالجملة — درجتان: من السلمون (تطابق 95% مع DNA البشري) ونباتية (بتخمير Lactobacillus). يبدأ الحد الأدنى للطلب من 10غ. مُثبت سريريًا لتجديد البشرة ومكافحة الشيخوخة وشفاء الجروح. نقاء >=90% / >=98%. COA لكل دفعة. سلاسل توريد معزولة.",
    featured: true,
    weight: 85,
    heroImage: "https://cdn.sanity.io/images/h5gs7zpr/production/b4cc6844a311825750575e2abda268007c0da203-2400x1792.webp",
    mainCategories: ["cosmetic-ingredients", "superfood"],
    antiAgingMechanisms: ["collagen-stimulant"],
    inciName: "Sodium DNA",
    applications: ["Cosmetics", "Nutraceuticals", "Dietary Supplements"]
  },
  {
    _id: "28549198-f5e7-46b3-975c-90586b2cb9e7",
    name: "Glabridin — Bulk Raw Material",
    slug: "glabridin",
    category: { name: "cosmetic-ingredients", slug: "cosmetic-ingredients" },
    categories: [{ name: "cosmetic-ingredients", slug: "cosmetic-ingredients" }],
    botanicalName: "Glabridin (from Glycyrrhiza glabra L. root)",
    purity: "≥ 90.0% (standard) / ≥ 98.0% (premium) — HPLC",
    activeIngredient: "Glabridin",
    casNumber: "59870-68-7",
    shortDescription: "Factory-direct Glabridin bulk powder (≥90% / ≥98% HPLC) — the gold-standard licorice-derived antioxidant & tyrosinase inhibitor for skin lightening. 16× stronger than kojic acid. Natural cosmetic ingredient with COA, MSDS per batch.",
    shortDescription_ru: "Глабридин оптом напрямую с производства (≥90%/≥98% HPLC) — золотой стандарт антиоксиданта и ингибитора тирозиназы из солодки для осветления кожи. В 16 раз сильнее койевой кислоты. Натуральный косметический ингредиент с COA и MSDS на партию.",
    shortDescription_es: "Glabridina a granel directa de fábrica (≥90%/≥98% HPLC) — el antioxidante e inhibidor de tirosinasa de referencia del regaliz para aclarar la piel. 16× más potente que el ácido kójico.",
    shortDescription_ar: "مسحوق غلابريدين خام مباشر من المصنع (≥90%/≥98% HPLC) — المعيار الذهبي لمضادات الأكسدة ومثبّطات التيروزيناز المستخلصة من العرقسوس لتفتيح البشرة.",
    featured: true,
    weight: 83,
    heroImage: "https://cdn.sanity.io/images/h5gs7zpr/production/012c62484bb9a830c541dee1727670cdd03e806d-1376x768.webp",
    mainCategories: ["cosmetic-ingredients"],
    antiAgingMechanisms: ["mmp-inhibitor"],
    inciName: "Glabridin",
    applications: ["Cosmetics", "Nutraceuticals", "Dietary Supplements"]
  },
  {
    _id: "47ae6004-26d8-4d9b-9e64-c8e0d7c64d15",
    name: "Spermidine — Bulk Raw Material",
    slug: "spermidine-bulk-raw-material",
    category: { name: "cosmetic-ingredients", slug: "cosmetic-ingredients" },
    categories: [{ name: "cosmetic-ingredients", slug: "cosmetic-ingredients" }, { name: "superfood", slug: "superfood" }],
    botanicalName: "Synthetic or naturally derived from wheat germ and soybean",
    purity: "≥ 99.0% — HPLC",
    activeIngredient: "Spermidine",
    casNumber: "124-20-9",
    shortDescription: "Factory-direct Spermidine bulk (≥99%) — a clinically studied natural polyamine that induces autophagy for cellular rejuvenation. Backed by a landmark 20-year human study.",
    shortDescription_ru: "Спермидин оптом (≥99%) напрямую от производителя — клинически изученный природный полиамин, индуцирующий аутофагию для клеточного омоложения.",
    shortDescription_es: "Espermidina a granel directa de fábrica (≥99%): una poliamina natural clínicamente estudiada que induce la autofagia para el rejuvenecimiento celular.",
    shortDescription_ar: "سبرميدين بالجملة مباشرة من المصنع (≥99%) — بوليامين طبيعي مدروس سريريًا يحفّز التحلل الذاتي لتجديد الخلايا.",
    featured: true,
    weight: 76,
    heroImage: "https://cdn.sanity.io/images/h5gs7zpr/production/47548813bd1840ab6011a6c9a5007cce94a02cc5-1408x768.jpg",
    mainCategories: ["cosmetic-ingredients", "superfood"],
    antiAgingMechanisms: ["collagen-stimulant"],
    inciName: "Spermidine",
    applications: ["Cosmetics", "Nutraceuticals", "Dietary Supplements"]
  },
  {
    _id: "59d05c5e-1d0d-4d93-ae86-4d12468885d4",
    name: "Apigenin — Bulk Raw Material",
    slug: "apigenin",
    category: { name: "cosmetic-ingredients", slug: "cosmetic-ingredients" },
    categories: [{ name: "cosmetic-ingredients", slug: "cosmetic-ingredients" }, { name: "superfood", slug: "superfood" }],
    botanicalName: "Matricaria chamomilla, Petroselinum crispum",
    purity: "≥98% (HPLC)",
    activeIngredient: "Apigenin",
    casNumber: "520-36-5",
    shortDescription: "Apigenin bulk powder (≥98% HPLC) directly from manufacturer — a naturally occurring flavonoid from chamomile and parsley. Clinically validated CD38 inhibitor that elevates cellular NAD+ levels.",
    shortDescription_ru: "Апигенин оптом (≥98% HPLC) напрямую от производителя — природный флавон из ромашки и петрушки. Клинически подтверждённый ингибитор CD38.",
    shortDescription_es: "Apigenina en polvo a granel (≥98% HPLC) directamente del fabricante: un flavonoide natural de la manzanilla y el perejil. Inhibidor de CD38 clínicamente validado.",
    shortDescription_ar: "مسحوق أبيجينين (≥98% HPLC) مباشرة من المصنّع — فلافونويد طبيعي من البابونج والبقدونس. مثبّط CD38 مُثبَت سريرياً.",
    featured: false,
    weight: 67,
    heroImage: "https://cdn.sanity.io/images/h5gs7zpr/production/dc7df656017110b1776e533fe9e1a0242cabc4c9-1024x1024.webp",
    mainCategories: ["cosmetic-ingredients", "superfood"],
    antiAgingMechanisms: ["mmp-inhibitor", "anti-glycation"],
    inciName: "Apigenin",
    applications: ["Cosmetics", "Nutraceuticals", "Dietary Supplements"]
  },
  {
    _id: "28b8f50e-b13f-4a9f-a19b-b9062d652338",
    name: "Ferulic Acid — Bulk Raw Material",
    slug: "ferulic-acid-bulk-raw-material",
    category: { name: "cosmetic-ingredients", slug: "cosmetic-ingredients" },
    categories: [{ name: "cosmetic-ingredients", slug: "cosmetic-ingredients" }, { name: "superfood", slug: "superfood" }],
    botanicalName: "Derived from rice bran and wheat",
    purity: "≥ 98.0% — HPLC",
    activeIngredient: "Ferulic Acid",
    casNumber: "1135-24-6",
    shortDescription: "Factory-direct Ferulic Acid bulk (≥98%) — the gold-standard phenolic antioxidant that doubles the photoprotective efficacy of Vitamins C and E.",
    shortDescription_ru: "Феруловая кислота оптом (≥98%) напрямую от производителя — золотой стандарт фенольного антиоксиданта, удваивающий фотозащитную эффективность витаминов C и E.",
    shortDescription_es: "Ácido ferúlico a granel directo de fábrica (≥98%): el antioxidante fenólico de referencia que duplica la eficacia fotoprotectora de las vitaminas C y E.",
    shortDescription_ar: "حمض الفيروليك بالجملة مباشرة من المصنع (≥98%) — مضاد أكسدة فينولي معياري يضاعف الفعالية الواقية من الأشعة لفيتاميني C وE.",
    featured: true,
    weight: 66,
    heroImage: "https://cdn.sanity.io/images/h5gs7zpr/production/4537ecbb6cadf8aa926ee3b62d0bd056cce393de-1200x896.webp",
    mainCategories: ["cosmetic-ingredients", "superfood"],
    antiAgingMechanisms: ["mmp-inhibitor"],
    inciName: "Ferulic Acid",
    applications: ["Cosmetics", "Nutraceuticals", "Dietary Supplements"]
  },
  {
    _id: "17ef5927-4203-4d43-aabd-a021f54ae192",
    name: "Asiaticoside — Bulk Raw Material",
    slug: "asiaticoside",
    category: { name: "cosmetic-ingredients", slug: "cosmetic-ingredients" },
    categories: [{ name: "cosmetic-ingredients", slug: "cosmetic-ingredients" }, { name: "superfood", slug: "superfood" }],
    botanicalName: "Centella asiatica (L.) Urb.",
    purity: "≥98%",
    activeIngredient: "Asiaticoside (≥95%)",
    casNumber: "16830-15-2",
    shortDescription: "Clinically proven wound-healing and collagen-boosting triterpenoid saponin from Centella asiatica. Available in 95%+ purity for cosmetic formulations.",
    shortDescription_ru: "Клинически доказанный тритерпеноидный сапонин из центеллы азиатской для заживления ран и стимуляции коллагена.",
    shortDescription_es: "Saponina triterpenoide clínicamente probada de Centella asiática que cicatriza heridas y aumenta el colágeno.",
    shortDescription_ar: "صابونين تريتيربينوي خماسي الحلقات مُثبت سريريًا لتسريع التئام الجروح وتعزيز الكولاجين من السنتيلا آسياتيكا.",
    featured: false,
    weight: 65,
    heroImage: "https://cdn.sanity.io/images/h5gs7zpr/production/cebc9aea7171c1270fb8b090eae2ac0688314728-1200x896.webp",
    mainCategories: ["cosmetic-ingredients", "superfood"],
    antiAgingMechanisms: ["collagen-stimulant"],
    inciName: "Asiaticoside",
    applications: ["Cosmetics", "Nutraceuticals", "Dietary Supplements"]
  },
  {
    _id: "0a11b6ac-9a04-451a-976b-55b4218588b0",
    name: "Turmeric Root Extract Powder",
    slug: "turmeric-root-extract-powder",
    category: { name: "superfood", slug: "superfood" },
    categories: [{ name: "superfood", slug: "superfood" }],
    botanicalName: "Synthetic curcumin",
    purity: "98% Curcumin (Synthetic)",
    activeIngredient: "Curcumin 98% (Synthetic)",
    casNumber: "458-37-7",
    shortDescription: "Factory-direct Turmeric Root Extract Powder standardized to 98% synthetic curcumin (CAS 458-37-7). Food/oral-grade bulk raw material for nutraceuticals.",
    shortDescription_ru: "Порошок экстракта куркумы со стандартизацией 98% синтетического куркумина (CAS 458-37-7). Сырьё оптом пищевого/перорального класса.",
    shortDescription_es: "Polvo de extracto de curcuma estandarizado a 98% de curcumina sintetica (CAS 458-37-7). Materia prima a granel grado alimenticio/oral.",
    shortDescription_ar: "مسحوق خالص الكركم المقاس إلى 98% كوركومين صناعي (CAS 458-37-7). مادة خام بالجملة درجة غذائية/فموية.",
    featured: false,
    weight: 55,
    heroImage: "https://cdn.sanity.io/images/h5gs7zpr/production/443423621bf738ed6cd3a486f40e867cd756496c-1376x768.jpg",
    mainCategories: ["superfood"],
    antiAgingMechanisms: [],
    inciName: "Turmeric Root Extract Powder",
    applications: ["Cosmetics", "Nutraceuticals", "Dietary Supplements"]
  },
  {
    _id: "128fe1a9-c8b8-485b-9fce-b475b6c8a023",
    name: "EGCG (Epigallocatechin Gallate) — Bulk Raw Material",
    slug: "egcg-epigallocatechin-gallate",
    category: { name: "cosmetic-ingredients", slug: "cosmetic-ingredients" },
    categories: [{ name: "cosmetic-ingredients", slug: "cosmetic-ingredients" }, { name: "superfood", slug: "superfood" }],
    botanicalName: "(−)-Epigallocatechin-3-O-gallate",
    purity: "≥ 98.0% (HPLC)",
    activeIngredient: "Epigallocatechin gallate (EGCG)",
    casNumber: "989-51-5",
    shortDescription: "Factory-direct EGCG bulk powder (≥98% HPLC) — the most bioactive green tea catechin for cosmetic and supplement manufacturing. Potent antioxidant, photoprotection, collagen preservation.",
    shortDescription_ru: "EGCG оптом (≥98% ВЭЖХ) напрямую от производителя — самый биоактивный катехин зелёного чая для косметического и пищевого производства.",
    shortDescription_es: "Polvo a granel de EGCG directo de fábrica (≥98 % HPLC): la catequina de té verde más bioactiva para la fabricación de cosméticos y suplementos.",
    shortDescription_ar: "مسحوق EGCG بالجملة (≥98% HPLC) — أكثر كاتشينات الشاي الأخضر نشاطاً حيوياً لتصنيع التجميل والمكملات.",
    featured: true,
    weight: 50,
    heroImage: "https://cdn.sanity.io/images/h5gs7zpr/production/5c4211130086309b4f8fb0cf4e807ef07ce6da14-1376x768.webp",
    mainCategories: ["cosmetic-ingredients", "superfood"],
    antiAgingMechanisms: ["mmp-inhibitor", "anti-glycation"],
    inciName: "Epigallocatechin Gallate",
    applications: ["Cosmetics", "Nutraceuticals", "Dietary Supplements"]
  },
  {
    _id: "7f581253-f3e2-4f6a-b3d1-d2b24039da1d",
    name: "PQQ Disodium Salt (Pyrroloquinoline Quinone) — Bulk Raw Material",
    slug: "pqq-disodium-salt",
    category: { name: "superfood", slug: "superfood" },
    categories: [{ name: "superfood", slug: "superfood" }],
    botanicalName: "Pyrroloquinoline quinone disodium salt",
    purity: "≥ 98.0% (HPLC)",
    activeIngredient: "Pyrroloquinoline quinone (PQQ)",
    casNumber: "122628-50-6",
    shortDescription: "Factory-direct PQQ disodium salt bulk powder (≥98% HPLC). The mitochondrial biogenesis cofactor — antioxidant potency surpassing vitamin C.",
    shortDescription_ru: "Пирролохинолинхинон динатриевая соль оптом (≥98% ВЭЖХ) напрямую от производителя. Кофактор митохондриального биогенеза.",
    shortDescription_es: "Polvo a granel de sal disódica PQQ directo de fábrica (≥98% HPLC). El cofactor de la biogénesis mitocondrial.",
    shortDescription_ar: "ملح بي كيو كيو ثنائي الصوديوم بالجملة (≥98% HPLC). العامل المرافق لتكوين الميتوكوندريا.",
    featured: true,
    weight: 48,
    heroImage: "https://cdn.sanity.io/images/h5gs7zpr/production/2301b95f0ee017cb76076264c19015e4cb9bcd09-1376x768.webp",
    mainCategories: ["superfood"],
    antiAgingMechanisms: ["collagen-stimulant"],
    inciName: "Pyrroloquinoline Quinone Disodium Salt",
    applications: ["Cosmetics", "Nutraceuticals", "Dietary Supplements"]
  },
  {
    _id: "0bb94dc5-e02b-4863-9d77-867f0b48fcd1",
    name: "Fullerene C60 — Bulk Raw Material",
    slug: "fullerene-c60",
    category: { name: "cosmetic-ingredients", slug: "cosmetic-ingredients" },
    categories: [{ name: "cosmetic-ingredients", slug: "cosmetic-ingredients" }],
    botanicalName: "Fullerene C60 (synthetic carbon allotrope)",
    purity: "≥99.5% (HPLC, standard grade); ≥99.9% (HPLC, premium grade)",
    activeIngredient: "Fullerene C60 (Buckminsterfullerene)",
    casNumber: "99685-96-8",
    shortDescription: "Fullerene C60 is a Nobel Prize-winning carbon nanomaterial acting as a radical sponge, neutralizing free radicals with up to 172x the antioxidant capacity of Vitamin C.",
    shortDescription_ru: "Фуллерен C60 — это удостоенный Нобелевской премии углеродный наноматериал, нейтрализующий свободные радикалы в 172 раза сильнее витамина C.",
    shortDescription_es: "Fullerene C60 es un nanomaterial de carbono ganador del Premio Nobel con hasta 172 veces la capacidad antioxidante de la vitamina C.",
    shortDescription_ar: "فوليرين C60 هو مادة نانوية كربونية حائزة على جائزة نوبل تفوق فيتامين C بـ172 ضعفًا.",
    featured: false,
    weight: 45,
    heroImage: "https://cdn.sanity.io/images/h5gs7zpr/production/6f241f5cdb9a30eb186d135d8e5d24ff52243416-1200x896.webp",
    mainCategories: ["cosmetic-ingredients"],
    antiAgingMechanisms: ["mmp-inhibitor"],
    inciName: "Fullerene C60",
    applications: ["Cosmetics", "Nutraceuticals", "Dietary Supplements"]
  },
  {
    _id: "dfeed6df-aee4-4b0a-b7ca-db47f2e76a3c",
    name: "GHK-Cu Copper Peptide Raw Powder | Cosmetic Grade",
    slug: "ghk-cu",
    category: { name: "cosmetic-ingredients", slug: "cosmetic-ingredients" },
    categories: [{ name: "cosmetic-ingredients", slug: "cosmetic-ingredients" }],
    botanicalName: "Copper Tripeptide-1",
    purity: "≥ 98.0% — HPLC",
    activeIngredient: "GHK-Cu / Copper Tripeptide-1",
    casNumber: "89030-95-5",
    shortDescription: "Factory-direct GHK-Cu (CAS 89030-95-5) blue copper peptide bulk powder for cosmetic manufacturing. ≥98% HPLC, copper assay per batch. Cold-chain global shipping. Clinically proven ECM remodeling and collagen booster.",
    shortDescription_ru: "GHK-Cu (CAS 89030-95-5) синий медный пептид оптом для косметического производства. ≥98% ВЭЖХ, анализ меди на каждую партию. Стимуляция ремоделирования матрикса и синтеза коллагена.",
    shortDescription_es: "Polvo a granel de péptido de cobre azul GHK-Cu (CAS 89030-95-5) directo de fábrica para la fabricación de cosméticos. ≥98% HPLC, ensayo de cobre por lote. Remodelación ECM y potenciador de colágeno.",
    shortDescription_ar: "GHK-Cu (CAS 89030-95-5) بودرة ببتيد نحاس أزرق خام لتصنيع التجميل. ≥98% HPLC وتحليل نحاس لكل شحنة. يعزز إعادة تشكيل المصفوفة والكولاجين.",
    featured: true,
    weight: 80,
    heroImage: "https://cdn.sanity.io/images/h5gs7zpr/production/2301b95f0ee017cb76076264c19015e4cb9bcd09-1376x768.webp",
    mainCategories: ["cosmetic-ingredients"],
    antiAgingMechanisms: ["collagen-stimulant"],
    inciName: "Copper Tripeptide-1",
    applications: ["Cosmetics", "Nutraceuticals", "Dietary Supplements"]
  },
  {
    _id: "snap-8-acetyl-octapeptide-3",
    name: "SNAP-8 (Acetyl Octapeptide-3) — Lipotec Anti-Wrinkle Octapeptide",
    slug: "snap-8-acetyl-octapeptide-3",
    category: { name: "cosmetic-ingredients", slug: "cosmetic-ingredients" },
    categories: [{ name: "cosmetic-ingredients", slug: "cosmetic-ingredients" }],
    botanicalName: "Acetyl Octapeptide-3",
    purity: "≥ 98.0% — HPLC",
    activeIngredient: "SNAP-8 / Acetyl Octapeptide-3",
    casNumber: "868844-74-0",
    shortDescription: "Buy high-purity wholesale SNAP-8 (Acetyl Octapeptide-3) bulk raw powder. Learn about its SNARE complex mechanism, formulation specs, and cosmetic applications for reducing expression lines.",
    shortDescription_ru: "Купить оптом чистый порошок SNAP-8 (Acetyl Octapeptide-3) высокой очистки. Механизм SNARE, спецификации для косметического производства и применение против мимических морщин.",
    shortDescription_es: "Compre polvo crudo a granel de SNAP-8 (acetiloctapéptido-3) al por mayor de alta pureza. Mecanismo SNARE, especificaciones de formulación y aplicaciones cosméticas antiarrugas.",
    shortDescription_ar: "اشتر مسحوق SNAP-8 (أستيل أوكتاببتايد-3) الخام بالجملة عالي النقاء. تعرّف على آلية مجمع SNARE وتطبيقاته التجميلية للتجاعيد التعبيرية.",
    featured: true,
    weight: 78,
    heroImage: "https://cdn.sanity.io/images/h5gs7zpr/production/47548813bd1840ab6011a6c9a5007cce94a02cc5-1408x768.jpg",
    mainCategories: ["cosmetic-ingredients"],
    antiAgingMechanisms: ["mmp-inhibitor"],
    inciName: "Acetyl Octapeptide-3",
    applications: ["Cosmetics", "Nutraceuticals", "Dietary Supplements"]
  }
];

export const MOCK_POSTS: SanityPost[] = [
  {
    _id: '6a54175c-2ba3-40e9-8482-0907920d4a48',
    title: 'NMN, NMNH, NAD+: Navigating the Global NAD Precursor Market',
    slug: 'nmn-nmnh-nad-global-market-trends',
    excerpt: 'The global NMN market earned about $380M in 2025, but the real story is regulatory fragmentation reshaping supply chains. My market analysis across the US, China, Japan, and EU, and where NMNH fits into the next cycle.',
    coverImage: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=600&auto=format&fit=crop&q=80' as any,
    featured: true,
    publishedAt: '2026-06-09T05:41:00.000Z',
    updatedAt: '2026-06-09T05:41:00.000Z',
    tags: ['Market Trends', 'Research', 'Regulatory'],
    readTime: 17,
    author: {
      name: 'Zhang Zhilin',
      credentials: 'B.S.'
    },
    meta_title: 'NMN NMNH NAD+ Market: NR vs NMN, Purity & Strategy',
    meta_description: 'NMN global market $380M. NR vs NMN comparison, purity benchmarks (HPLC, heavy metals, endotoxin), NMNH next-gen NAD+ precursor, resveratrol synergy.'
  },
  {
    _id: '78115189-c9c5-4b3b-ba42-cd494048d5e5',
    title: "PQQ: The Market's Most Underrated Mitochondrial Molecule",
    slug: 'pqq-mitochondrial-health-market-trend',
    excerpt: 'PQQ is rare among mitochondrial actives — it both protects existing mitochondria and triggers new mitochondrial biogenesis. At $47.7M, the PQQ market is 1/16th the size of CoQ10. That ratio is not a failure — it is a timing signal.',
    coverImage: 'https://images.unsplash.com/photo-1576086213369-97a306d36557?w=600&auto=format&fit=crop&q=80' as any,
    featured: true,
    publishedAt: '2026-06-05T01:21:00.000Z',
    updatedAt: '2026-06-05T01:25:00.000Z',
    tags: ['Market Trends', 'Ingredient Spotlight'],
    readTime: 14,
    author: {
      name: 'Zhang Zhilin',
      credentials: 'B.S.'
    },
    meta_title: 'PQQ Mitochondrial Health: Market Opportunity Analysis | GINKVORA',
    meta_description: 'PQQ triggers mitochondrial biogenesis via PGC-1α and protects via Nrf2. Market analysis with verified data: $47.7M PQQ vs $760M CoQ10. Strategy for brand owners.'
  },
  {
    _id: '55dfc21f-4df2-4237-a440-052d8026ec73',
    title: 'Glabridin Before and After: A 12-Week Transformation Timeline',
    slug: 'glabridin-12-week-timeline',
    excerpt: "Glabridin doesn't work overnight — that's exactly why it's effective. Week-by-week timeline of melanin, inflammation, and collagen changes, so you can set accurate customer expectations and keep them using your product past week 3.",
    coverImage: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=600&auto=format&fit=crop&q=80' as any,
    featured: true,
    publishedAt: '2025-12-04T04:45:00.000Z',
    updatedAt: '2025-12-04T04:45:00.000Z',
    tags: ['Industry News', 'Ingredient Spotlight', 'Research', 'Quality & Testing', 'Formulation Tips'],
    readTime: 12,
    author: {
      name: 'Clara Wang',
      credentials: 'M.S.'
    },
    meta_title: 'Glabridin Before and After: 12-Week Brightening Timeline',
    meta_description: 'What happens to melanin, inflammation, and collagen each week when glabridin enters a formula. Week-by-week biological timeline for cosmetic formulators.'
  },
  {
    _id: '9e03963f-b30e-47b7-a409-de2ffb4dd554',
    title: "GHK-Cu Copper Peptide: A Formulator's Technical Guide",
    slug: 'ghk-cu-formulation-technical-guide',
    excerpt: 'GHK-Cu looks simple — until you formulate it. My lab-level guide to keeping this copper peptide stable across serums, creams, gels, eye creams, and scalp products.',
    coverImage: 'https://images.unsplash.com/photo-1512290900676-26c2a4d0b5ae?w=600&auto=format&fit=crop&q=80' as any,
    featured: true,
    publishedAt: '2026-06-08T02:32:00.000Z',
    updatedAt: '2026-06-08T02:32:00.000Z',
    tags: ['Ingredient Spotlight', 'Formulation Tips', 'Research'],
    readTime: 17,
    author: {
      name: 'Clara Wang',
      credentials: 'M.S.'
    },
    meta_title: "GHK-Cu Copper Peptide: Formulator's Technical Guide",
    meta_description: 'GHK-Cu formulation: serums, creams, gels, eye creams, hair growth products. pH control, ingredient compatibility, copper verification, sourcing checklist.'
  },
  {
    _id: '05f06e32-255c-41e9-a430-83decd96add8',
    title: 'Free Radicals vs. Quercetin: The Antioxidant Mechanism Explained for Non-Scientists',
    slug: 'quercetin-antioxidant-free-radicals',
    excerpt: 'Free radicals cause 10,000+ daily oxidative strikes, accelerating aging. Quercetin combats this by directly scavenging reactive molecules and activating the Nrf2 pathway—outperforming Vitamin C and E in ORAC capacity.',
    coverImage: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=600&auto=format&fit=crop&q=80' as any,
    featured: true,
    publishedAt: '2026-05-14T01:18:00.000Z',
    updatedAt: '2026-07-02T01:12:43.000Z',
    tags: ['Ingredient Spotlight', 'Research', 'Formulation Tips'],
    readTime: 8,
    author: {
      name: 'Clara Wang',
      credentials: 'M.S.'
    },
    meta_title: 'Quercetin Antioxidant Benefits: Free Radical & Nrf2 Defense…',
    meta_description: 'Quercetin combats oxidative stress by scavenging free radicals and activating the Nrf2 pathway. Outperforms Vitamins C and E in ORAC capacity.'
  },
  {
    _id: '08fa644d-8c46-42a5-9e85-0dbde5147508',
    title: 'What Is NMN? A Raw-Material Scientist Breaks Down the Mechanism',
    slug: 'nmn-mechanism',
    excerpt: "NMN is a direct NAD+ precursor with real mechanism but honest limits. A raw-material scientist explains what it is, how it's absorbed, what the data prove, and how to buy it well.",
    coverImage: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=600&auto=format&fit=crop&q=80' as any,
    featured: true,
    publishedAt: '2026-07-08T01:59:00.000Z',
    updatedAt: '2026-07-08T01:59:00.000Z',
    tags: ['Ingredient Spotlight', 'Research', 'Longevity', 'NAD+', 'Formulation Tips'],
    readTime: 8,
    author: {
      name: 'Clara Wang',
      credentials: 'M.S.'
    },
    meta_title: 'What Is NMN? The Mechanism, Honestly',
    meta_description: "NMN is a direct NAD+ precursor. A raw-material scientist explains how it's absorbed, what human trials prove, and how to choose raw material."
  },
  {
    _id: 'quercetin-senolytic-anti-aging-id',
    title: 'Quercetin as a Senolytic: How It Clears Zombie Cells to Slow Biological Aging',
    slug: 'quercetin-senolytic-anti-aging',
    excerpt: 'Quercetin selectively targets senescent cells, downregulating anti-apoptotic pathways (BCL-2, PI3K/AKT) and mitigating the harmful SASP secretory profile.',
    coverImage: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=600&auto=format&fit=crop&q=80' as any,
    featured: true,
    publishedAt: '2026-06-15T01:00:00.000Z',
    updatedAt: '2026-06-15T01:00:00.000Z',
    tags: ['Ingredient Spotlight', 'Research', 'Longevity', 'Senolytics'],
    readTime: 10,
    author: {
      name: 'Clara Wang',
      credentials: 'M.S.'
    },
    meta_title: 'Quercetin Senolytic Mechanism & Cellular Rejuvenation',
    meta_description: 'Discover how Quercetin acts as a natural senolytic compound to eliminate senescent zombie cells and mitigate SASP inflammation.'
  },
  {
    _id: 'quercetin-safety-dosage-id',
    title: 'Quercetin Safety Profile: Dosage, Drug Interactions, and Who Should Avoid It',
    slug: 'quercetin-safety-dosage',
    excerpt: 'Comprehensive safety assessment for B2B formulators: dosage guidelines, CYP3A4 drug interactions, renal considerations, and GRAS status.',
    coverImage: 'https://images.unsplash.com/photo-1576086213369-97a306d36557?w=600&auto=format&fit=crop&q=80' as any,
    featured: false,
    publishedAt: '2026-06-20T01:00:00.000Z',
    updatedAt: '2026-06-20T01:00:00.000Z',
    tags: ['Safety & Regulatory', 'Formulation Tips', 'Dosage'],
    readTime: 9,
    author: {
      name: 'Clara Wang',
      credentials: 'M.S.'
    },
    meta_title: 'Quercetin Safety Profile & Dosage Guidelines',
    meta_description: 'Evidence-based safety guide for Quercetin supplementation: recommended daily dosage, drug-interaction risks, and regulatory compliance.'
  }
];

export const MOCK_SITE_SETTINGS = {
  siteName: 'GINKVORA',
  tagline: 'Pure Nature, Proven Science',
  contactEmail: 'inquiry@ginkvora.com',
  phone: '+86 13201818603',
  address: {
    street: 'Xi\'an International Trade & Logistics Park',
    city: 'Xi\'an',
    country: 'China'
  },
  certifications: [
    { name: 'ISO 9001:2015', href: '#' },
    { name: 'GMP', href: '#' },
    { name: 'Halal', href: '#' },
    { name: 'Kosher', href: '#' },
    { name: 'Organic', href: '#' }
  ],
  stats: [
    { value: '500', suffix: '+', label: 'Active Ingredients' },
    { value: '3', suffix: '+', label: 'Years of Expertise' },
    { value: '50', suffix: '+', label: 'Countries Served' },
    { value: '99', suffix: '%', label: 'Purity Standard' }
  ]
};

export const MOCK_AUTHORS = [
  {
    _id: 'author-1',
    name: 'Clara Wang',
    title: 'Lead Scientific Formulation Specialist',
    title_ru: 'Ведущий специалист по научным рецептурам',
    credentials: 'M.S.',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=300&auto=format&fit=crop&q=80',
    bio: 'Specializing in bioactive extraction, cellular delivery mechanisms, and anti-aging ingredient formulation.',
    bio_ru: 'Специализируется на экстракции биоактивных веществ, механизмах клеточной доставки и рецептурах антивозрастных ингредиентов.'
  },
  {
    _id: 'author-2',
    name: 'Zhang Zhilin',
    title: 'Senior Ingredient & Market Analyst',
    title_ru: 'Старший аналитик ингредиентов и рынка',
    credentials: 'B.S.',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300&auto=format&fit=crop&q=80',
    bio: 'Focusing on global botanical ingredient supply chains, market trends, and regulatory compliance.',
    bio_ru: 'Фокусируется на глобальных цепочках поставок растительных ингредиентов, рыночных тенденциях и нормативном соответствии.'
  },
  {
    _id: 'author-3',
    name: 'Atwood Wang',
    title: 'Global Regulatory & Compliance Director',
    title_ru: 'Директор по глобальному регулированию и комплаенсу',
    credentials: 'RAC, MS in Global Regulatory Affairs',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=300&auto=format&fit=crop&q=80',
    bio: 'Expert in FDA GRAS, EU Novel Food, REACH compliance, and global supplement regulations.',
    bio_ru: 'Эксперт в области FDA GRAS, EU Novel Food, соответствия REACH и глобального регулирования пищевых добавок.'
  },
  {
    _id: 'author-4',
    name: 'Dr. Mia Chen',
    title: 'Head of Quality Assurance & Purity Validation',
    title_ru: 'Руководитель отдела контроля качества и валидации чистоты',
    credentials: 'PhD in Analytical Chemistry, CQE',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=300&auto=format&fit=crop&q=80',
    bio: 'Specializing in HPLC chromatography, heavy metal testing, and cGMP quality control standards.',
    bio_ru: 'Специализируется на ВЭЖХ хроматографии, тестировании тяжелых металлов и стандартах контроля качества cGMP.'
  }
];

